### ISSUE TITLE
Backstage 1.11.x and SearchResult changes

### ISSUE THREAD

**Issue by djl197** [K-Phoen/backstage-plugin-confluence#164]
We have been exploring this plugin and have just upgraded Backstage to 1.11.x

I think the SearchResults setup has changed:
```
<SearchResult>
    <CatalogSearchResultListItem icon={<CatalogIcon />} />
    <TechDocsSearchResultListItem icon={<DocsIcon />} />
</SearchResult>
```

The 
```
ConfluenceResultListItem
```

Does not match - and I cant get the changes described in Readme to work (have tried some simple changes).
We will continue to investigate - but sharing for visibility.

**Comment by ahochsteger** [comment]
We've been exploring this plugin as well using Backstage 1.11.1 and face the same problem.
